defaults:
  - override hydra/job_logging: disabled

_target_: src.types.ReplayExperimentConfig
verbose: false
baseline_data_dir: ../embedding_models/
model_seed: 0
override_model_seed: true
exp_name: human_replay_example
replay_data_dir: results/human_data/human_data_pkl
replay_as_decoder: true
replay_as_interceptor: true
models:
  - _target_: src.types.BaselineModel
    model_key: GloVe
    model_id: GloVe
    global_guess: true
    baseline_k: 16

  - _target_: src.types.LocalModel
    model_key: llama3.1_8B
    model_id: meta-llama/Meta-Llama-3.1-8B-Instruct
    urls: 
        - http://localhost:8000/v1
    max_tokens: 750
    temperature: 0.6
    model_seed: 0