defaults:
  - override hydra/job_logging: disabled

_target_: src.types.ExperimentConfig
num_episodes: 1
env_seed: [0]
verbose: false
baseline_data_dir: ../embedding_models/
exp_name: api_gpt4_example
confirm_include_api_models: true  # Warning: will incur API costs
models:    
  - _target_: src.types.OpenAIModel
    model_key: gpt-4o
    model_id: gpt-4o
    api_key_name: OPENAI_PRIMARY_KEY  # OpenAI key name, stored in .env file
    temperature: 0.6
    max_tokens: 750
    # use_azure: true
    # api_version: 2024-06-01
    # api_host_name: AZURE_OPENAI_HOST  # Azure OpenAI host name, stored in .env file