defaults:
  - override hydra/job_logging: disabled

_target_: src.types.HumanExperimentConfig
num_episodes: 1
env_seed: [1789]
verbose: false
baseline_data_dir: ../embedding_models/
exp_name: human_play_example
confirm_include_api_models: true  # Warning: will incur API costs
models: # Exactly three models required, in order: encoder, decoder, interceptor
  - _target_: src.types.Human
    model_key: alice
    model_id: human

  - _target_: src.types.OpenAIModel
    model_key: gpt-4o
    model_id: gpt-4o
    api_key_name: OPENAI_PRIMARY_KEY  # OpenAI key name, stored in .env file
    temperature: 0.6
    max_tokens: 750
    
  - _target_: src.types.OpenAIModel
    model_key: gpt-4o
    model_id: gpt-4o
    api_key_name: OPENAI_PRIMARY_KEY  # OpenAI key name, stored in .env file
    temperature: 0.6
    max_tokens: 750